Remove broken tests - closes issue #44
HelloFax/hellosign-nodejs-sdk pull request #46
Opened 2019-03-28 17:20 UTC by Framinus

Removed old functional test suite, removed hardcoded config information from mock-functional test suite, and updated README.md instructions to run functional test suite.

2019-04-01 20:17 UTC, nathanbuchar commented on test/mock-functional/account.js
> -var hellosign = require('/Users/derek/Documents/sdks/hellosign-nodejs-sdk/lib/hellosign.js')({
Oh noooooooo

Thanks for cleaning that up

2019-04-01 20:19 UTC, nathanbuchar requested changes

2019-04-01 20:19 UTC, nathanbuchar commented on test/mock-functional/account.js
> +var hellosign = require('../../lib/hellosign.js')({
`.js` extensions are implicit in Node.js, let's drop all of these extensions.

2019-04-03 15:12 UTC, Framinus commented
I made the requested changes and updated the unit test file to remove the .js extensions there, as well.

2019-04-05 17:32 UTC, nathanbuchar approved these changes

2019-04-05 17:32 UTC, merged