Updating README.md file to include the npm initializer
HelloFax/hellosign-nodejs-sdk pull request #61
Opened 2020-04-24 20:23 UTC by hazemhamedhs

Upon Stork's request, she wanted us to call out this first step `npm init` to initialize npm prior to install HS node SDK. So, users can avoid running into an issue when trying to cd node_modules/hellosign-sdk. So, we added that one note only:
# Optionally, to scaffolding your package.json first
npm init

2020-04-24 21:19 UTC, latoyazamill requested changes
Update # Optionally, to scaffolding your package.json first to # Optionally, to scaffold your package.json first

2020-11-17 18:13 UTC, latoyazamill submitted a review, later dismissed

2020-11-18 18:40 UTC, nathanbuchar commented
I'm not entirely sure this is really necessary based on the requirements mentioned in the PR description.

> So, users can avoid running into an issue when trying to `cd node_modules/hellosign-sdk`.

When running `npm install hellosign-sdk`, npm will automatically create a `node_modules` folder in the current directory, just not a `package.json`. All `npm init` will do is create a `package.json` in the folder.

Maybe I've missed something?

2020-11-18 19:10 UTC, hazemhamedhs commented
@nathanbuchar, you have not missed anything. Our main call out was to assist non-node Primary developer to better initiate the package before installing. This is us going the extra mile to educate non-node API customers and can be closed with the need to getting pushed.

2020-11-18 19:33 UTC, nathanbuchar commented
In this case, instead of taking on the onus of educating developers about npm, perhaps we should link out to npm documentation instead, like this doc: https://docs.npmjs.com/downloading-and-installing-packages-locally

2020-11-19 00:44 UTC, hazemhamedhs commented
I like your approach. Where would you see the best location for that url in the README file?

2020-11-19 18:39 UTC, nathanbuchar commented
Probably just a note on line 17 (above the code block) which says something to this effect:

> First time using npm? Read more about installing npm packages [here](https://docs.npmjs.com/downloading-and-installing-packages-locally).

2020-11-20 03:08 UTC, nathanbuchar approved these changes

2020-11-20 03:08 UTC, merged